apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: kairokube-producer:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: url
        - name: MESSAGE_PAYLOAD
          value: '{"event":"order.updated","order_id":"k8s-demo","status":"ready"}'
        - name: PUBLISH_RATE_MSG_PER_SEC
          value: "2"
        - name: MAX_MESSAGES
          value: "0"
