apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: migration-manager-pods
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migration-manager-kubelet-proxy
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: migration-manager-pods-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: migration-manager
    namespace: default
roleRef:
  kind: Role
  name: migration-manager-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: migration-manager-kubelet-proxy-binding
subjects:
  - kind: ServiceAccount
    name: migration-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: migration-manager-kubelet-proxy
  apiGroup: rbac.authorization.k8s.io
